parity /mnt/disks/parity1/snapraid.parity

content /var/snapraid/content
content /mnt/disks/disk-ssd1/.snapraid/content
content /mnt/disks/disk-ssd2/.snapraid/content
content /mnt/disks/disk-wd931/.snapraid/content
content /mnt/disks/disk-hgst1/.snapraid/content
content /mnt/tm/walter/.snapraid/content
content /mnt/tm/marissa/.snapraid/content

data d1 /mnt/disks/disk-ssd1
data d2 /mnt/disks/disk-ssd2
data d3 /mnt/disks/disk-wd931
data d4 /mnt/disks/disk-hgst1
data tmwalter /mnt/tm/walter
data tmmarissa /mnt/tm/marissa

exclude *.unrecoverable
exclude /tmp/
exclude /lost+found/
exclude .SnapRAID
exclude .snapraid/
exclude .Trash-*/
exclude .Trash/
